import { useState, useEffect } from 'react'
import ReactMarkdown from 'react-markdown'
import { generateReport } from '../utils/appsScriptApi'

export default function ReportPage({ module, state, onComplete, onBack }) {
  const [loading, setLoading] = useState(true)
  const [reportData, setReportData] = useState(null)
  const [error, setError] = useState(null)

  useEffect(() => {
    // Get report from state - it's already generated by the Apps Script backend
    const existingReport = state.modules[module.id]?.report
    if (existingReport && existingReport.trim().length > 0) {
      setReportData(existingReport)
      setLoading(false)
      return
    }
    
    // If no report, show empty state
    setLoading(false)
  }, [module.id, state.modules])

  // Custom components for ReactMarkdown to match our CSS design system
  const MarkdownComponents = {
    h3: ({ node, children, ...props }) => {
      const text = String(children).toLowerCase()
      if (text.includes('guidance')) {
        return <div className="guidance-box__label mt-6">{children}</div>
      }
      return <h4 className="report-section__heading mt-6" {...props}>{children}</h4>
    },
    p: ({ node, children, ...props }) => {
      // Check if this paragraph is right after a 'Guidance' heading
      const prevNode = node.previousSibling
      if (
        prevNode && 
        prevNode.tagName === 'h3' && 
        prevNode.children[0]?.value?.toLowerCase().includes('guidance')
      ) {
        return <div className="guidance-box__text">{children}</div>
      }

      // Check for Identity Statement (usually quotes)
      if (String(children).startsWith('"I am') || String(children).startsWith('“I am')) {
        return <div className="identity-statement">{children}</div>
      }

      return <p className="report-section__body mt-2" {...props}>{children}</p>
    },
    ul: ({ node, children, ...props }) => (
      <div className="report-section__body mt-2"><ul {...props}>{children}</ul></div>
    ),
    li: ({ node, children, ...props }) => <li {...props}>{children}</li>,
  }

  // Wrap the Guidance content in the box using CSS structure
  // The easiest way to box it is to let the H3 and P render, and we wrap it in a div if needed, 
  // but since our CSS requires `.guidance-box`, and ReactMarkdown renders linearly, 
  // we can preprocess the text slightly to wrap the Guidance section if we want, 
  // or just rely on the classes above. For simplicity, we'll preprocess the markdown string 
  // to wrap the Guidance section in a blockquote that we can style as the guidance box!

  const preProcessedData = reportData
    ? reportData.replace(/### Guidance([\s\S]*)/i, (match, content) => {
        const lines = content.trim().split('\n')
        return `> **GUIDANCE**\n> \n` + lines.map(line => `> ${line}`).join('\n')
      })
    : ''

  const FinalMarkdownComponents = {
    ...MarkdownComponents,
    blockquote: ({ node, children, ...props }) => (
      <div className="guidance-box mt-6" {...props}>{children}</div>
    ),
    strong: ({ node, children, ...props }) => {
      if (String(children) === 'GUIDANCE') return <div className="guidance-box__label">Guidance</div>
      return <strong {...props}>{children}</strong>
    }
  }

  return (
    <>
      <div className="module-header">
        <div className="module-header__bar">
          <div className="module-header__left">
            <button className="module-header__back" onClick={onBack} disabled={loading}>←</button>
            <div>
              <div className="module-header__label">Module {module.id} | Complete</div>
              <div className="module-header__title">{module.reportTitle}</div>
            </div>
          </div>
        </div>
        <div className="progress-bar">
          <div className="progress-bar__fill" style={{ width: '100%', background: 'var(--color-complete)' }} />
        </div>
      </div>

      <div className="page-container report-page">
        <div className="card report-card">
          <h2 className="report-title">{module.reportTitle || module.title}</h2>
          <div className="report-subtitle">Module {module.id} Report • {module.title}</div>

          {loading ? (
            <div className="loading-state">
              <div className="loading-spinner" />
              <div className="loading-text">
                Loading your report...
              </div>
            </div>
          ) : error ? (
            <div className="loading-state">
              <div className="loading-text" style={{ color: 'red' }}>Error: {error}</div>
              <button className="btn btn--outline mt-4" onClick={() => window.location.reload()}>Retry</button>
            </div>
          ) : !reportData ? (
            <div className="loading-state">
              <div className="loading-text">
                Report is being generated. Please wait...
                <br />
                <button className="btn btn--outline mt-4" onClick={() => window.location.reload()}>Refresh Page</button>
              </div>
            </div>
          ) : (
            <div className="report-content">
              <ReactMarkdown components={FinalMarkdownComponents}>
                {preProcessedData}
              </ReactMarkdown>
              
              <div className="mt-8 text-center" style={{ display: 'flex', gap: '1rem', justifyContent: 'center' }}>
                <button className="btn btn--primary" style={{ width: 'auto', padding: '12px 32px' }} onClick={onBack}>
                  ← Back To Dashboard
                </button>
                <button 
                  className="btn btn--outline" 
                  style={{ width: 'auto', padding: '12px 32px' }} 
                  onClick={async () => {
                    if (confirm("Are you sure you want to regenerate this report with AI?")) {
                      setLoading(true);
                      setError(null);
                      try {
                        const result = await generateReport(state.userEmail, module.id);
                        if (result.success && result.report) {
                          setReportData(result.report);
                          onComplete(module.id, result.report);
                        } else {
                          setError("Failed to generate report");
                        }
                      } catch (err) {
                        setError(err.message || "Error generating report");
                      } finally {
                        setLoading(false);
                      }
                    }
                  }}
                >
                  Regenerate Report ↻
                </button>
              </div>
            </div>
          )}
        </div>
      </div>
    </>
  )
}
